### ISSUE TITLE
enable github pages

### ISSUE THREAD

**Issue by satr14washere** [Avdan-OS/Demo#5]
enable Github pages so that we can just go to the website instead of downloading source code

**Comment by Froxcey** [comment]
This demo is meant to be hosted on a VPS and embedded in avdanos.com. I don't see the need for GitHub page, as normal users will just use the new demo embedded on the website when it's ready and developers will need to download the source code anyways.

**Comment by CodeHeister** [comment]
Pigpot has deployed it. Thanks him a lot.

Till demo isn't on the website, it may be deployed to give viewers an opportunity to see it without cloning even if it's working out of box.
